### ISSUE TITLE
PyPi gpu release

### ISSUE THREAD

**Issue by pikarpov-LANL** [pikarpov-LANL/Sapsan#63]
There is an error in the "version" name because of which the gpu release is failing to be published. In addition, '-gpu' keeps being added to the release.

`.github/workflows/pypi-release.yml`

Error:
```
Checking dist/sapsan-v0.1.3_gpu_gpu-py3-none-any.whl: PASSED
Checking dist/sapsan-v0.1.3-gpu-gpu.tar.gz: PASSED
Uploading distributions to https://upload.pypi.org/legacy/
Uploading sapsan-v0.1.3_gpu_gpu-py3-none-any.whl

  0%|          | 0.00/64.2k [00:00<?, ?B/s]
 12%|█▏        | 8.00k/64.2k [00:00<00:01, 45.2kB/s]
100%|██████████| 64.2k/64.2k [00:00<00:00, 168kB/s] 
NOTE: Try --verbose to see response content.
HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/
'v0.1.3-gpu-gpu' is an invalid value for Version. Error: Start and end with a letter or numeral containing only ASCII numeric and '.', '_' and '-'. See https://packaging.python.org/specifications/core-metadata for more information.
```

**Comment by IceKhan13** [comment]
Closed in https://github.com/pikarpov-LANL/Sapsan/pull/65 
Pypi does not allow extra naming in version if it's not alpha, beta, dev releases. So, no gpu etc.
So now you have 2 packages 
https://pypi.org/project/sapsan-gpu/#history
https://pypi.org/project/sapsan/

+ logo in pypi description is fixed :)
