### ISSUE TITLE
JOSS documentation / paper revisions

### ISSUE THREAD

**Issue by kburns** [pikarpov-LANL/Sapsan#99]
Hello, as a part of my review of the Sapsan JOSS paper (https://github.com/openjournals/joss-reviews/issues/3199), here are some questions and comments relating to the documentation and JOSS draft:

Documentation:

- [x] Scope: Overall I think the scope of the software should be specified more clearly, particularly in the web documentation. E.g., is the goal to make a unified interface to models from various ML frameworks that are relevant for learning subgrid closures? The description "Sapsan is a pipeline for easy Machine Learning implementation in scientific projects" is overly broad and the documentation should reflect the current features.

- [x] Need: It's stated that Sapsan makes ML easy, but it would be good to describe some of the specific workflow difficulties that Sapsan helps users avoid, perhaps data manipulation and normalization or hyperparameter selection?

- [x] Installation: It looks like pip installing Sapsan in a clean Python 3.9 environment (on MacOS at least) fails due to an issue with scikit-image wheels for 3.9 (perhaps related to https://github.com/scikit-image/scikit-image/issues/5060). Until this upstream issue is fixed, it should be noted that the pip installation requires Python <= 3.8.

- [x] Examples: Many of the abstraction implementation links on the JOSS-branch README are broken (e.g. "3d dataset" and all the "experiment" links).

- [x] Functionality: The majority of the necessary documentation (functionality and API documentation) is located in the Wiki, but this is not linked from the README page in the JOSS branch.

- [x] Tests: There do not appear to be any automated tests.  A command-line testing interface (e.g. using pytest) that returns a binary pass/fail signal would be preferable to the current suggested test of running one of the notebook examples.

- [x] Community guidelines: There do not appear to be any contribution/support guidelines on the README or Wiki.

Software paper

- [x] Summary: The summary should be expanded to more clearly describe the scope and functionality of the current codebase.

- [x] State of the field: specific comparisons should be made to existing software packages / workflows.

- [x] Writing: I think the paper should be more specific about how the package can be used. Results from two test problems are shown, but the paper should better indicate what options the user can modify and what general model space is covered by the code, beyond just the two specific setups used in the examples.

- [x] References: the references should be expanded to include the ML packages that Sapsan wraps / relies on (e.g pytorch, scikit, etc.).

**Comment by pikarpov-LANL** [comment]
## Documentation
#### Scope:
- I agree that I should have a tighter focus, which Sapsan already has. There is no reason to make it general. I edited the README accordingly.

#### Need:
- README updated
#### Installation:
- I had !=3.9 statement in the setup.py + a pip clarification of python = 3.7 and 3.8. Thus, it is strange that Sapsan was installed fine in python=3.9. Nonetheless, I put in an explicit statement of <=3.8
#### Examples:
- JOSS branch has not been merged for a while as I only keep the paper there. In either case - updated.
#### Functionality:
- Link to the Wiki is now front and center!
#### Tests:
- There has always been a few unit tests for data loading and unit tests with all current ML models included in Sapsan through jupyter notebooks via pytest. Is there anything else I should add?
#### Community guidelines:
- I have added a section describing how to contribute to Sapsan. Please review [Community Guidelines](https://github.com/pikarpov-LANL/Sapsan/wiki/Community-Guidelines).

**Comment by pikarpov-LANL** [comment]
## Software paper

#### Summary:

- I included more details/examples of Sapsan’s capabilities in the Summary. Please let me know if this is enough or if I should expand further.

#### State of the field:

- As far as I am concerned, there is nothing like Sapsan bringing ML and turbulence modeling. I have tightened the focus on turbulence modeling in the paper, instead of the general applications in physical sciences.

#### Writing:

- I added a bit more text to the Framework section to indicate what the user can adjust in Sapsan. Please let me know if this is sufficient or if I should include a separate section.

#### References:

- Added references to the core packages under Dependencies in section Framework of the paper.

**Comment by kburns** [comment]
Thanks for addressing all of these points!  I'm trying to install the latest version now in a conda environment with python 3.8.10, but I'm getting the error:

`ERROR: Package 'sapsan' requires a different Python: 3.8.10 not in '<=3.8,>=3.7'`

I think the specifier should be changed to `<3.9` instead of `<=3.8` so that all `3.8.*` releases are included.

**Comment by pikarpov-LANL** [comment]
I fixed up the requirements issue and released a new version with various bug fixes - please make sure you install the latest version (v0.2.10). 

Good note on testing! I will add it through Click interface and work on the manuscript edits you mentioned later tonight.

**Comment by pikarpov-LANL** [comment]
Please check out the latest v0.3.0 - I have made significant changes to the CLI, further simplifying getting started on a custom project/estimator + added the testing routines to the CLI. Manuscript changes per your suggestions have been made as well.

**Comment by kburns** [comment]
Thanks! I downloaded the latest (v0.4.0) and tried to run the tests, but it failed saying

```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/kburns/Software/miniconda3/envs/sapsan38/lib/python3.8/site-packages/sapsan/examples/cnn_example.ipynb'
```

I think the issue is that `setuptools.find_packages()` only looks for / includes `*.py` files, so the entire examples directory and all the `*.ipynb` don't get included in the builds for PyPI.

**Comment by pikarpov-LANL** [comment]
Thank you! I forgot to test the PyPi release locally, better write a test for it. I just fixed the issue in `v0.4.1`, please check it out.

**Comment by kburns** [comment]
Thanks! Tests are passing for me now. Just a few very minor points on the new draft (line numbers refer to the latest whedon-generated PDF):

- [ ] Typo line 86: "Loos" -> "Loss"
- [ ] Typo line 131: "10243" -> "1024^3" (maybe this is just a rendering problem?)
- [ ] For both examples, can you say qualitatively how much filtering was done to produce the training data from the DNS? That's really useful for understanding how much of the dynamics the ML closure is responsible for.

**Comment by pikarpov-LANL** [comment]
1. Fixed
2. It is a rendering issue - I am not sure what to do since it shows up fine on the paper.md on github (using html <sup>3</sup>, but ^ doesn't work either)
3. Added the exact filtering amount I used

**Comment by kburns** [comment]
Great, everything looks good to me. Might want to check with some other folks in the main thread if you can't get the rendering worked out for the PDF, not sure about that one myself. Thanks a lot for your patience with the review!

**Comment by pikarpov-LANL** [comment]
Glad to hear! Your feedback has certainly been appreciated - the code and the paper are in a much better shape now. I will check with the editor on the superscript rendering issue.
